/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AXIOM_DATASET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AXIOM_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET_DEVELOPMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET_STAGING": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EvalyBackendService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "EvalyBackendVPC": {
      "type": "sst.aws.Vpc"
    }
    "EvalyDB": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "EvalyDBVPC": {
      "type": "sst.aws.Vpc"
    }
    "Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_API_URL_DEVELOPMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_API_URL_STAGING": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_URL_DEVELOPMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_URL_STAGING": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WEB_PUBLIC_URL_DEVELOPMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WEB_PUBLIC_URL_STAGING": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}