/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NEXT_PUBLIC_API_URL_DEVELOPMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_API_URL_STAGING": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_URL_DEVELOPMENT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_URL_STAGING": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}