/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_BUCKET_NAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_CDN_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EVALY_AWS_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EVALY_AWS_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_GENERATIVE_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainWebsite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NEXT_PUBLIC_POSTHOG_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_SUPABASE_ANON_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_SUPABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}