ALTER TABLE "account" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "session" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "verification" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organization" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organizer" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "test" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "test_section" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "code_editor_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "date_time_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fill_blank_segment" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "formula_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hotspot_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "matching_pair" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "matrix_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "media_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "slider_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "text_field_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_template" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "test_invitation" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "test_attempt" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "test_attempt_answer" ENABLE ROW LEVEL SECURITY;