export const backendSecrets = {
  // common
  ENVIRONMENT: $app.stage,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  AXIOM_API_TOKEN: process.env.AXIOM_API_TOKEN,
  AXIOM_DATASET_NAME: process.env.AXIOM_DATASET_NAME,

  //development
  WEB_PUBLIC_URL_DEVELOPMENT: process.env.WEB_PUBLIC_URL_DEVELOPMENT,
  DATABASE_URL_DEVELOPMENT: process.env.DATABASE_URL_DEVELOPMENT,
  BETTER_AUTH_SECRET_DEVELOPMENT: process.env.BETTER_AUTH_SECRET_DEVELOPMENT,
 
  //staging
  WEB_PUBLIC_URL_STAGING: process.env.WEB_PUBLIC_URL_STAGING,
  DATABASE_URL_STAGING: process.env.DATABASE_URL_STAGING,
  BETTER_AUTH_SECRET_STAGING: process.env.BETTER_AUTH_SECRET_STAGING,
};

export const frontendSecrets = {
  //common
  NEXT_PUBLIC_ENVIRONMENT: $app.stage,

  //development
  NEXT_PUBLIC_URL_DEVELOPMENT: process.env.NEXT_PUBLIC_URL_DEVELOPMENT,
  NEXT_PUBLIC_API_URL_DEVELOPMENT: process.env.NEXT_PUBLIC_API_URL_DEVELOPMENT,

  //staging
  NEXT_PUBLIC_URL_STAGING: process.env.NEXT_PUBLIC_URL_STAGING,
  NEXT_PUBLIC_API_URL_STAGING: process.env.NEXT_PUBLIC_API_URL_STAGING,
};
