export const backendSecrets = {
  // common
  ENVIRONMENT: $app.stage,
  GOOGLE_CLIENT_ID: new sst.Secret("GOOGLE_CLIENT_ID"),
  GOOGLE_CLIENT_SECRET: new sst.Secret("GOOGLE_CLIENT_SECRET"),
  AXIOM_API_TOKEN: new sst.Secret("AXIOM_API_TOKEN"),
  AXIOM_DATASET_NAME: new sst.Secret("AXIOM_DATASET_NAME"),

  //development
  WEB_PUBLIC_URL_DEVELOPMENT: new sst.Secret("WEB_PUBLIC_URL_DEVELOPMENT"),
  DATABASE_URL_DEVELOPMENT: new sst.Secret("DATABASE_URL_DEVELOPMENT"),
  BETTER_AUTH_SECRET_DEVELOPMENT: new sst.Secret("BETTER_AUTH_SECRET_DEVELOPMENT"),
 
  //staging
  WEB_PUBLIC_URL_STAGING: new sst.Secret("WEB_PUBLIC_URL_STAGING"),
  DATABASE_URL_STAGING: new sst.Secret("DATABASE_URL_STAGING"),
  BETTER_AUTH_SECRET_STAGING: new sst.Secret("BETTER_AUTH_SECRET_STAGING"),
};

export const frontendSecrets = {
  //common
  NEXT_PUBLIC_ENVIRONMENT: $app.stage,

  //development
  NEXT_PUBLIC_URL_DEVELOPMENT: new sst.Secret("NEXT_PUBLIC_URL_DEVELOPMENT"),
  NEXT_PUBLIC_API_URL_DEVELOPMENT: new sst.Secret("NEXT_PUBLIC_API_URL_DEVELOPMENT"),

  //staging
  NEXT_PUBLIC_URL_STAGING: new sst.Secret("NEXT_PUBLIC_URL_STAGING"),
  NEXT_PUBLIC_API_URL_STAGING: new sst.Secret("NEXT_PUBLIC_API_URL_STAGING"),
};
